language: node_js
node_js:
  - "node"
install:
  - yarn install
script:
  - if [[ $TRAVIS_EVENT_TYPE != 'pull_request' ||  $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then npm run chromatic; fi
branches:
  only:
    - master